// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtnOTQTSo-Tk4fSHFA5Dt3g_LNFjvxctQ',
    appId: '1:483009989253:web:2428b4321ff5b2898bb7ec',
    messagingSenderId: '483009989253',
    projectId: 'via-store',
    authDomain: 'via-store.firebaseapp.com',
    storageBucket: 'via-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhuavn_kEc70thsERxXhnq9ZgObKJaCs',
    appId: '1:483009989253:android:d0c374fe20bd06268bb7ec',
    messagingSenderId: '483009989253',
    projectId: 'via-store',
    storageBucket: 'via-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSco10ZZ9LTO4GGSBud43Lgov_T2XH6o',
    appId: '1:483009989253:ios:d2638c74b266af2a8bb7ec',
    messagingSenderId: '483009989253',
    projectId: 'via-store',
    storageBucket: 'via-store.appspot.com',
    iosBundleId: 'com.example.estudoDeCaso',
  );
}
